/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.apps.anuncis;

import java.awt.MenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import org.iesapp.framework.pluggable.DockingFrameworkApp;
import org.iesapp.framework.pluggable.SysTray;
import org.iesapp.framework.pluggable.WindowManager;
import org.iesapp.framework.util.CoreCfg;

/**
 *
 * @author Josep
 */
public class AnuncisApp extends DockingFrameworkApp {

    /**
     * Creates new form FitxesApp
     */
    public AnuncisApp(String[] args) {
        super(args);
        this.appNameId="Anuncis";
        this.appDisplayName="Anuncis";
        this.appDescription="Programa d'anuncis";
        this.setIconImage(new ImageIcon(getClass().getResource("/org/iesapp/apps/anuncis/icons/bulb.gif")).getImage());
        initComponents();
        
        this.jStatusBar.setVisible(false);
        this.jMenuBar1.setVisible(false);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/org/iesapp/apps/anuncis/icons/bulb.gif"));
        stray = new SysTray(this, icon, "iesDigital "+CoreCfg.VERSION+": Anuncis");
        this.setIconImage(icon.getImage());
        stray.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                AnuncisApp.this.windowManager.setLastDisplayMode();
                //System.out.println("maximixe");
            }
        });
        MenuItem menuClose = new MenuItem("Tancar");
        menuClose.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                AnuncisApp.this.exitApp();
            }
        });
        
        stray.getPopupMenu().add(menuClose);

        requiredModuleName = "org.iesapp.modules.anuncis.AnuncisModule";  
        requiredJar = "org-iesapp-modules-anuncis.jar";  
        appClass = getClass();
        initializeFramework();
        
    }
 
    
    //Define desired window close behaviour
    @Override
    public void formWindowClosing(WindowEvent evt) {
           windowManager.setDisplayMode(WindowManager.MODE_TOOLBAR);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    
   
    public static void main(String[] args) {
           SwingUtilities.invokeLater(new DisplayApp(args));     
    }
     
    private static class DisplayApp implements Runnable
    {
            private final String[] args;
            public DisplayApp(String[] args)
            {
                this.args = args;
            }
            
            @Override
            public void run() {
             
                 AnuncisApp app = new AnuncisApp(args);
//                 app.setExtendedState(JFrame.ICONIFIED);
//                 app.setVisible(true);
               
            }
        
    }
}
